// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whnsljxfognbaheqnqaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobnNsanhmb2duYmFoZXFucWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTc1NjYsImV4cCI6MjA2OTY5MzU2Nn0.2L459iSOvL9xBVWvRLSF-MoYsKs0TiE6O3HQtM5cvnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);